apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinewebsite-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-website
  template:
    metadata:
      labels:
       app: online-website
    spec:
      containers:
      - name: devops
        image: rahrthr12/devops-online-website
        ports:
          - name: online
            containerPort: 4200